# Generated by Django 3.2.5 on 2022-05-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=45)),
                ('item_label', models.CharField(max_length=45)),
                ('item_disambiguator', models.CharField(blank=True, default='', max_length=45)),
            ],
            options={
                'ordering': ['item_name', 'item_label', 'item_disambiguator'],
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('item_name', 'item_label', 'item_disambiguator'), name='unique_item'),
        ),
    ]
