# Generated by Django 3.2.5 on 2022-05-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iteminfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_amount', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['warehouse', 'assignment_amount'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_number', models.CharField(max_length=20)),
                ('warehouse_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['warehouse_name', 'warehouse_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('warehouse_name', 'warehouse_number'), name='unique_warehouse'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='iteminfo.item'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='iteminfo.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('assignment_id', 'warehouse', 'item'), name='unique_assignment'),
        ),
    ]
